Use Vendetta for dependency management
joushou/sshmuxd pull request #15
Opened 2017-03-02 18:50 UTC by lclc

Vendetta is a minimal tool for managing the dependencies in the vendor directory of a go project.
It adds all Go packages as git submodules, to make sure updates of Go packages don't break the build.

See: https://github.com/dpw/vendetta

Built on top of https://github.com/joushou/sshmuxd/pull/14, but I can also do it without the dependencies from there.

2017-03-02 23:27 UTC, kennylevinsen requested changes
Just a minor comment on the README. Will also merge the other PR first, as this contains both commits.

2017-03-02 23:27 UTC, joushou commented on README.md
> +	git clone https://github.com/joushou/sshmuxd.git && cd sshmuxd
If you do the following, you don't need "mkdir", a "cd", or the submodule update you added later:
```shell
git clone --recursive https://github.com/joushou/sshmuxd.git $GOPATH/src/github.com/joushou/sshmuxd
```

2017-03-02 23:27 UTC, joushou commented on README.md
> +	git submodule update --init --recursive
If you add `--recursive` to the clone, this becomes unnecessary.

2017-03-02 23:27 UTC, joushou commented on README.md
> +	go install
go build is implicit in go install - maybe just let that be the only step?

2017-03-02 23:27 UTC, joushou commented on .gitmodules
> +	url = https://gopkg.in/yaml.v2
Damn, that's a long list. I guess this is pulled in by viper? Not complaining, just... Damn.

2017-03-02 23:29 UTC, joushou commented on README.md
> +	git clone https://github.com/joushou/sshmuxd.git && cd sshmuxd
Note that I think the "cd to final sshmuxd folder" kinda belongs down in the build/install section.

2017-03-02 23:30 UTC, joushou commented
I'm entirely fine with using vendored submodules. I didn't previously because my dependencies where quite minimal (and I was lazy at the time - work and all). As long as the tool is merely an external convenience that users/developers won't *need* to use, then I'm all okay with it.

2017-03-03 13:41 UTC, lclc commented
Thanks for the feedback, I've changed the README accordingly.

I plan to update & rebase this PR again after the other gets merged.

2017-03-04 13:26 UTC, joushou commented
Cool, I'll merge after the other one. Git should be smart enough to not need a rebase.

2017-03-05 15:39 UTC, kennylevinsen approved these changes

2017-03-05 15:39 UTC, merged